Fix bug when using forest_minimize() since scikit-learn 1.2
Previous error message:
InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.